on: 
  push:
    branches: [rcoh-docs]
    
env:
  rust_version: 1.51.0
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_version }}
      - name: Generate docs
        run: mkdir docs-new && touch docs-new/docs.txt # cargo doc --target-dir ../docs-new --no-deps
        working-directory: sdk
      - name: Push the docs 
        run: |
          git checkout -B gh-pages
          rm docs
          mv docs-new docs
          git config --local user.email "docs-action@github.com"
          git config --local user.name "GitHub Action (docs)"
          git add docs
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -m 'Add docs'
          git push
